version: '4.0'

services:
  web:
    build: ./mysite
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mysite/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:14.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=djgirl2
      - POSTGRES_PASSWORD=djgirl2
      - POSTGRES_DB=isplab3v11

volumes:
  postgres_data: